command:
  - uvicorn
  - backend.main:app
  - --host
  - 0.0.0.0
  - --port
  - 8000

env:
  - name: NODE_ENV
    value: production
  - name: DATABRICKS_HOST
    valueFrom: context
  - name: DATABRICKS_CLIENT_ID
    valueFrom: context
  - name: DATABRICKS_CLIENT_SECRET
    valueFrom: context
